language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
sudo: false
env:
  matrix:
    secure: QJnMTnzyn+VpT4cvu+kw3dTdzj17j2FsRxz6HXm9MrAn4HfjOhoKkLBX8pNDKmvPnG4SwQc3OjQLksbKeB/36caou9iXYmR5ByzarSH8BTMtMzMk6l13lYLtJchoh7ZqN8PPbOxXB/DnQM1qX4Ig09zORsHMGj5hDloWe7QOLTIc4buuJz8RrP4Sg5lJg8fKjmj0CAmRmB40yFWWW16Cg4OYO1Qq3rBGHV58CxBiyl6Z4AqZjqhJbpPHP4VSZ2dfnBPQ1iwaKZ4ojmUPUdyMD5GJkuBEki504aEg14MFP0YZeVPLId9LK549la9AkMQSrdehap5eWD4naPRu5AKQwoyzsIPKZtehj4/rkUhW0UCH6Yb/AfmmJS75gonrsUHxfNw5VPSe7O4plbyoEOmlSwv2GJ31vk4N2C8oKsciZltfowfRs7CHJ2M6Zc5FLGj2EEGeL2pvAVST3YTVQ2SHaWHHj6cvDg0duh055RoETtkasADEcTx4ECKbgSZjR9fNFbLtxE1Tqs5He/Dz7cSqpFiVMBdtKNCEX+AZJw6K4PEElwmsl7rQ+mBJsdvLOcsBPyfkVxOHHInlH13ysRCg4yKnge1/rVNDZr+KUKmp0jiHfIo0GG3KajBSiyXRAktKMjF/VeEAm1AOwi+pzmeMQ2bhxfiJNRGgudQVtQeQxDs=
